### ISSUE TITLE
Consider res.sendNotImplemented() instead of res.send501()

### ISSUE THREAD

**Issue by andyfleming** [zesty-io/response-express-middleware#3]
Would it be better to provide names instead of codes for sending default responses?

`res.send501()` vs `res.sendNotImplemented()`

(I'm not completely sold either way. I think there are trade-offs

**Comment by shrunyan** [comment]
I like using the number code for a few reasons.
- shorter
- makes them distinct (e.g. scanning code for responses is easier)
- no discussion around exact signature to use. e.g. `res.sendNotImpl` vs `res.sendNotImplemented`
